################################################################################
#
# Driver registrations
#
################################################################################

UK_DRIV_QEMU_BASE := $(UK_DRIV_BASE)/qemu

$(eval $(call import_lib,$(UK_DRIV_QEMU_BASE)/ivshmem))
